spring.application.name= sepse
spring.datasource.url=jdbc:mysql://localhost:3307/protocolo_sepse?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=B@5qu3t3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
